=== Haploanddog/lmtarea4/Actividad2.dtd
<!ELEMENT clientes (cliente)>
	<!ELEMENT cliente (direccion, telefono*, tipo_cliente, factura+)>
	    <!ATTLIST cliente cod_cliente ID #REQUIRED>
        <!ELEMENT direccion (#PCDATA)>
            <!ATTLIST direccion nombre_via CDATA #REQUIRED>
            <!ATTLIST direccion num_via CDATA #REQUIRED>
            <!ATTLIST direccion localidad CDATA #REQUIRED>
            <!ATTLIST direccion provincia CDATA #REQUIRED>
            <!ATTLIST direccion cod_postal CDATA #REQUIRED>
        <!ELEMENT telefono (#PCDATA)>
            <!ATTLIST telefono tipo_tfno (particular | direccion | rrhh | contabilidad) #REQUIRED>
        <!ELEMENT tipo_cliente (empresa| particular)>
        <!ELEMENT empresa (nombre_apellidos, razon_social, web?, CIF)>
        <!ELEMENT particular (nombre_apellidos, NIF)>
            <!ELEMENT nombre_apellidos (#PCDATA)>
            <!ELEMENT razon_social (#PCDATA)>
            <!ELEMENT web (#PCDATA)>
            <!ELEMENT CIF (#PCDATA)>
            <!ELEMENT NIF (#PCDATA)>
        <!ELEMENT factura (fecha, num_factura, forma_pago, fecha_vencimiento, producto*, cuantia)>
            <!ELEMENT fecha (#PCDATA)>
                <!ATTLIST fecha type (date|dias) #FIXED "date">
            <!ELEMENT num_factura (#PCDATA)>
            <!ELEMENT forma_pago (#PCDATA)>
            <!ELEMENT fecha_vencimiento (#PCDATA)>
                <!ATTLIST fecha_vencimiento type (date|dias) #FIXED "dias">
            <!ELEMENT producto (cantidad, nombre_producto, precio_unitario)>
                <!ATTLIST producto cod_producto NMTOKEN #REQUIRED>
                <!ELEMENT cantidad (#PCDATA)>
                <!ELEMENT nombre_producto (#PCDATA)>
                <!ELEMENT precio_unitario (#PCDATA)>
                    <!ATTLIST precio_unitario moneda (EUR) #FIXED "EUR">
            <!ELEMENT cuantia (subtotal, iva, total)>
                <!ELEMENT subtotal (#PCDATA)>
                    <!ATTLIST subtotal moneda (EUR) #FIXED "EUR">
                <!ELEMENT iva (#PCDATA)>
                <!ELEMENT total (#PCDATA)>
                    <!ATTLIST total moneda (EUR) #FIXED "EUR">

=== Haploanddog/lmtarea4/actividad2_dtd.xml
<!--Ya que necesitamos el archivo actividad2.dtd, tenemos que marcar 'no' en 'standalone'. Aunque si no lo hubiese escrito, el valor por defecto hubiera sido el mismo-->
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Para enlazar con un archivo dtd externo incluiremos el nombre del archivo en el -->
<!DOCTYPE clientes SYSTEM "actividad2.dtd">
<clientes>
	<cliente>
		<codigo_cliente>E1234</codigo_cliente>
		<!--Ya que no importa el orden de los campos nombre_via, num_via,..., serán atributos-->
		<direccion nombre_via="Calle Romero" num_via="1" 
		localidad = "Córdoba" provincia ="Córdoba" 
		cod_postal="14003"></direccion>
		<telefono>957520744</telefono>
		<tipo_cliente>
			<empresa>
				<nombre_apellidos>Juan Ramírez Sánchez</nombre_apellidos>
				<razon_social>Restaurante Pepe de la Judería</razon_social>
				<web></web>
				<CIF>b14978647</CIF>
			</empresa>
		</tipo_cliente>	
		<factura>
			<fecha>19/01/2022</fecha>
			<num_factura>EMP-22-1234</num_factura>
			<forma_pago>Efectivo</forma_pago>
			<fecha_vencimiento>28 días</fecha_vencimiento>
			<producto>
				<cantidad>30</cantidad>
				<nombre_producto>Parqueoliva Serie OrO</nombre_producto>
				<cod_producto>PAR-SER-ORO</cod_producto>
				<precio_unitario>12.00</precio_unitario>
			</producto>
			<producto>
				<cantidad>12</cantidad>
				<nombre_producto>Rincón de la Subbética</nombre_producto>
				<cod_producto>RIN-CON-SUB</cod_producto>
				<precio_unitario>18.95</precio_unitario>
			</producto>
			<producto>
				<cantidad>10</cantidad>
				<nombre_producto>La joya del Monte</nombre_producto>
				<cod_producto>JOY-DEL-MON</cod_producto>
				<precio_unitario>69.95</precio_unitario>
			</producto>
			<cuantia>
				<subtotal>1286.90</subtotal>
				<iva>21</iva>
				<total>1557.15</total>
			</cuantia>
		</factura>
	</cliente>
</clientes>
